/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.sekolah.utshana;

/**
 *
 * @author devel
 */
public class DataSiswa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DataSiswa.class.getName());

    /**
     * Creates new form form1
     */
    public DataSiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        kelasPanel = new javax.swing.JPanel();
        nisLabel = new javax.swing.JLabel();
        nisTextField = new javax.swing.JTextField();
        namaSiswaLabel = new javax.swing.JLabel();
        namaSiswaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kelasComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nisLabel.setText("NIS");

        nisTextField.setText("jTextField1");
        nisTextField.addActionListener(this::nisTextFieldActionPerformed);

        namaSiswaLabel.setText("Nama Siswa");

        namaSiswaTextField.setText("jTextField1");

        jLabel3.setText("Kelas");

        kelasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        kelasComboBox.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                kelasComboBoxComponentAdded(evt);
            }
        });
        kelasComboBox.addActionListener(this::kelasComboBoxActionPerformed);

        javax.swing.GroupLayout kelasPanelLayout = new javax.swing.GroupLayout(kelasPanel);
        kelasPanel.setLayout(kelasPanelLayout);
        kelasPanelLayout.setHorizontalGroup(
            kelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelasPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(kelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nisLabel)
                    .addComponent(jLabel3)
                    .addComponent(namaSiswaLabel))
                .addGap(27, 27, 27)
                .addGroup(kelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaSiswaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        kelasPanelLayout.setVerticalGroup(
            kelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelasPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(kelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nisLabel)
                    .addComponent(nisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(kelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaSiswaLabel)
                    .addComponent(namaSiswaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(kelasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(338, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kelasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kelasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelasComboBoxComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_kelasComboBoxComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasComboBoxComponentAdded

    private void kelasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasComboBoxActionPerformed

    private void nisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nisTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DataSiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> kelasComboBox;
    private javax.swing.JPanel kelasPanel;
    private javax.swing.JLabel namaSiswaLabel;
    private javax.swing.JTextField namaSiswaTextField;
    private javax.swing.JLabel nisLabel;
    private javax.swing.JTextField nisTextField;
    // End of variables declaration//GEN-END:variables
}
