/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.sekolah.utshana;

import view.sekolah.utshana.DataSiswa;


/**
 *
 * @author devel
 */
public class FormUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormUtama.class.getName());

    /**
     * Creates new form formData
     */
    public FormUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        menuUtama = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dataSiswaMenuItem = new javax.swing.JMenuItem();
        dataKelasMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout menuUtamaLayout = new javax.swing.GroupLayout(menuUtama);
        menuUtama.setLayout(menuUtamaLayout);
        menuUtamaLayout.setHorizontalGroup(
            menuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        menuUtamaLayout.setVerticalGroup(
            menuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Master Data");

        dataSiswaMenuItem.setText("Data Siswa");
        dataSiswaMenuItem.addActionListener(this::dataSiswaMenuItemActionPerformed);
        jMenu1.add(dataSiswaMenuItem);

        dataKelasMenuItem.setText("Data Kelas");
        dataKelasMenuItem.addActionListener(this::dataKelasMenuItemActionPerformed);
        jMenu1.add(dataKelasMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuUtama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuUtama)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataSiswaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataSiswaMenuItemActionPerformed
        // TODO add your handling code here:
        DataSiswa dataSiswa = new DataSiswa();
        menuUtama.add(dataSiswa);
        dataSiswa.setVisible(true);
    }//GEN-LAST:event_dataSiswaMenuItemActionPerformed

    private void dataKelasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataKelasMenuItemActionPerformed
        // TODO add your handling code here:
        DataKelas dataKelas = new DataKelas();
        menuUtama.add(dataKelas);
        dataKelas.setVisible(true);
    }//GEN-LAST:event_dataKelasMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dataKelasMenuItem;
    private javax.swing.JMenuItem dataSiswaMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JDesktopPane menuUtama;
    // End of variables declaration//GEN-END:variables
}
